### ISSUE TITLE
@hyperswarm/* vs hyperdiscovery

### ISSUE THREAD

**Issue by jvntf** [hyperswarm/discovery#8]
Hello, I am working on a project that uses [hypercore](https://github.com/mafintosh/hypercore) and should make that data available to the network over Dat. I am wondering if someone can briefly explain the differences and / or benefit of using `@hypersarm/network` and `@hyperswarm/discovery` over [hyperdiscover](https://github.com/karissa/hyperdiscovery). From examples they seem to do the same thing but I get the sense that hyperswarm has more functionality. Thanks!

**Comment by RangerMauve** [comment]
`hyperswarm` is the new networking stack being built up for the Dat ecosystem. It's not totally stable yet but it should speed things up and improve p2p connectivity once it's finished.

`hyperdiscovery` is using the old networking stack, [discovery-swarm](https://www.npmjs.com/package/discovery-swarm), paired with some [default settings](https://github.com/datproject/dat-swarm-defaults) to connect to the Dat P2P networking. Right now you should use `hyperdiscovery` if you want something more stable, and `hyperswarm` if you want to try out the new stuff.

**Comment by jvntf** [comment]
thanks @RangerMauve!
